language: groovy

cache:
  directories:
    - $HOME/.gradle/caches/

before_install:
- curl -s http://get.sdkman.io | bash
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sdk install grails 3.1.9

script:
  - grails test-app --stacktrace
  - grails war

after_success:
  - label=$(./get_version)
  - mv build/libs/rest-api-*.war churchconnect_rest-api-$label.war
  - ls churchconnect_rest-api-*.war

addons:
  artifacts:
    paths: $(ls churchconnect_rest-api-*.war)
    target_paths: releases
    permissions: public-read
